version: "3.7"
services:
  nginx:
    image: nginx:1.19.5
    networks:
      - network
    volumes:
      - /home/custom_conf/nginx.conf:/etc/nginx/nginx.conf
      - static-volume:/data/static
      - media-volume:/data/media
    ports:
      - 80:80
  django_container_gunicorn:
    image: michael_shop_image:1
    networks:
      - network
    volumes:
      - static-volume:/home/michael-shop/staticfiles
      - media-volume:/home/michael-shop/media
    secrets:
      - DJANGO_SECRET_KEY
      - POSTGRES_PASSWORD
    depends_on:
      - db
      - nginx
  db:
    image: postgres:13.5
    networks:
      - network
    volumes:
      - postgres-database:/var/lib/postgresql/data/
    secrets:
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: michael_shop
      POSTGRES_USER: michael
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD
  

networks:
  network:

volumes:
  static-volume:
  media-volume:
  postgres-database:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  POSTGRES_PASSWORD:
    external: true